/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import java.util.Observable;
import java.util.Observer;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import chatroomlibrary.FileInfo;
import client.controller.ChatController;
import javax.swing.SwingUtilities;

/**
 *
 * @author daniel
 */
public class FilesView extends javax.swing.JPanel implements Observer {

    private static final long serialVersionUID = 1L;

    private ChatController controller;

    /**
     * Creates new form FilesView
     */
    public FilesView(ChatController controller) {
        this.controller = controller;
        controller.addObserver(this);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();

        jMenuItem1.setText("Request File");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItem1);

        jTree.setModel(null);
        jTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMouseClicked(evt);
            }
        });
        jTree.setRootVisible(false);

        jScrollPane2.setViewportView(jTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                        .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();
        FileInfo fileInfo = (FileInfo) selectedNode.getUserObject();
        controller.requestFile(fileInfo);
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTreeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTreeMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            int row = jTree.getClosestRowForLocation(evt.getX(), evt.getY());
            jTree.setSelectionRow(row);
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();
            if (selectedNode.isLeaf()) {
                FileInfo fileInfo = (FileInfo) selectedNode.getUserObject();

                if (!fileInfo.isDirectory())
                    jPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }// GEN-LAST:event_jTreeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree;

    // End of variables declaration//GEN-END:variables
    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof String) {
            String str = (String) arg;
            switch (str) {
            case "update-files":
                setFiles(controller.getFiles());
                break;
            default:
                break;
            }
        }
    }

    private void setFiles(DefaultMutableTreeNode files) {
        jTree.setModel(new DefaultTreeModel(files));
    }
}
